### PR TITLE
Webnative filecoin

### PR DESCRIPTION
**Pull request by dholms**
Alrighty think this is decent for an intial API. It's mostly just dummy data for addresses/balances. But does some error handling for balances & some internal state changes as well so the app looks like it's actually doing something :stuck_out_tongue: 

I'm thinking we have an initialization api like:
```ts
import filecoin from 'webnative-filecoin'
const fs = await webnative.initialize(...)
const wallet = await filecoin.getWallet(fs)
```
and that `wallet` is your go to hub for interactions.
```ts
await wallet.getBalance()
await wallet.fundProvider(amount)
await wallet.getProviderBalance()
await wallet.getAddress()
```
Currently handwaving over permissions. We'll add that in soon :sweat_smile: 

I opted to remove some of the `fp-ts` stuff, because many of these functions are user facing and they shouldn't be required to use that library and interact with the concepts to use our stuff. `fp-ts` is great for internal use, but external error handling should probably be the familiar js try-catch.

I also simplified balances to be `number`s instead of `bigint`s. I'm not totally convinced of this change, it makes it simpler to interact with as a developer but can be lossy :thinking:

Next steps: hooking this up to the server & start messing around with actually signing txs

### CODE REVIEW

**Comment by benjaminbollen** [comment]
Looks good!

> If the filecoin app only ever manages one keypair, we can combine wallet and keychain into a single class that manages all of the state

I'm in favour of merging wallet and keychain. (At least I have used "keychain" and "wallet" interchangeably, and opted for "keychain" to be more general (OAuth and other keys) )

I suggest keys are written to a separate directory 'floofs/private/Keychain/creator/name/pubkey.json'; for now we can even just write 'account.json' and have one key. Should be generalisable later then. suggested helper function here https://github.com/fission-suite/filecoin-backup/commit/b68b00056b9d1764f37ecd31fb5c38693ea58899 

> I opted to remove some of the fp-ts stuff

agreed, it s only for internal use

> I also simplified balances to be numbers instead of bigints. I'm not totally convinced of this change, it makes it simpler to interact with as a developer but can be lossy

a good compromise here, can be to internally deal with `attoFil` in BigInt (or string); but provide `display` functions, which round to `FIL as number` with some accuracy

on functions such as `transfer` this is perhaps less ideal. Here we could have the function take attoFIL, eg `transfer(amount: BigInt)`; and provide a helper function `toAttoFil = (amountInFil: number): BigInt`. Does that seem reasonable?

**Comment by dholms** [comment]
Should definitely workshop with others brooke/steven/james on semantics for the keychain
that sounds about right, but I'm wondering if we could simplify a bit and just have it stored at `wnfs/private/keychain/pubkey`. But there might be some trickery around permissioning an app to read/write the correct pubkey without first looking at the app folder :thinking: 

why does it need to be `.json`? couldn't it just be the raw bytes of the private key?

**Comment by benjaminbollen** [comment]
> just have it stored at `wnfs/private/keychain/pubkey.`

I would strongly be inclined to separate the keychain for different applications; that's why the proposal to follow the same path separation as we already for `Apps`, ie. `private/Keychain/creator/name` directory.

to make this explicit, and sketch how this could look for the backup app as a wallet; and third party apps:
- private key for the Filecoin backup app would be stored for alice under `alice.fission.name/private/Keychain/Fission/Backup/t3abc..124.json`
- the backup app gets WNFS permissions from auth lobby for the above directory.

the reason I would not throw all keys of all apps together, is because we dont have to (and is better data hygiene in general): let's look ahead to how a 3rd party app (eg. Photos album app) could ask the backup app access to "use and store on Filecoin":
- the Photos album app wants to access Filecoin, so it redirects to the wallet (backup app) to request a session; the relation here is equivalent to that of `(photos -> auth lobby)`, but now to request a "filecoin/cap:session" resource.
- on redirected to backup app with permissions request, and user confirms, backup app delegates a UCAN for a key session to the photos app; and it can share the private key `t3abc..124.json` encrypted as params, the same way the AES key is shared for read access to the file tree.
- a picture of how this could look like https://whimsical.com/20210225-backupapp-resource-flow-4eNnsVWXWXW6pCiUGdezYi

**Comment by benjaminbollen** [comment]
> why does it need to be .json? couldn't it just be the raw bytes of the private key?

the json format could provide flexibility to write meta data to the same file, and use it as a micro (semi-static) datastore;
eg. for t3abc..124.json, I would think it valuable to write following params
```
{
  "version": 0,
  "network": "filecoin/main",
  "privateKeyUser": "0xabc..def",
  "cosignerKeySeed": 0x94d..7aa",
  "didCosigner": "did:key:z123..456",
  "publicKeyCosigner": "t3def..876",
  "publicKeyAggregated": "t3826..d1a"
}
```
I think it s even interesting to write dynamic data (eg. formulated messages (sent or not) to the chain, derived from that you'd have an upperbound for the nonce). Starting with a static file is a great start though, and we can get all dynamic state over network requests.

Storing the (opt. encrypted) `cosignerKeySeed` here, secures and simplifies the cosigner, as the cosigner doesn't need to store a DB of BLS keys for each user, and keep securely encrypted it on its end.

Instead when Alice makes a request to sign, she can send the `cosignerKeySeed` along with the request. The private BLS key the cosigner uses to cosign can be generated from
```
privateKeyCosigner =  Blake2b(
   rsaSign( did:key:zAlice + publicKeyUser + cosignerKeySeed, didPrivateKeyCosigner ),
   32); 
```

**Comment by bgins** [comment]
@dholms Looking through the SDK calls and the initialization makes perfect sense. `wallet.getBalance()` and `wallet.getAddress()` look good for getting information on the FIL wallet.

Following our discussion this morning, I'm wondering if `wallet.fundProvider(amount)` and `wallet.getProviderBalance()` still make sense? Do we need to give special treatment to the provider or are they just another address? My thoughts are that we can bring them in for now. We may not need them in phase 2, but we might want them in phase 3.

**Comment by dholms** [comment]
yeah I think we'll want
`wallet.fundProvider(amount)` as well as `wallet.send(address, amount)`

We still need `wallet.getProviderBalance()` right? because users send money to our provider, and we need to know how much each user has sent.

The provider is going to be holding funds for multiple users, so this data would come from a DB (or crawling the chain for txs between a user and the provider)

**Comment by bgins** [comment]
Yep, that makes sense. They'll want to see their balance on the provider so they can make storage deals.

We'll probably use provider balance information to allow or block them from making storage deals in the UI.

**Pull request merged**
